default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: Root@123
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: spree_commerce_development

test:
  <<: *default
  database: spree_commerce_test

production:
  <<: *default
  database: spree_commerce_production
  username: spree_commerce
  password: <%= ENV['SPREE_COMMERCE_DATABASE_PASSWORD'] %>
